### ISSUE TITLE
False positive at sigs.k8s.io/kind/pkg/internal/env/term.go@L75

### ISSUE THREAD

**Issue by cardil** [pierDipi/unicode-control-characters-action#3]
This check raises a false positive at:

https://github.com/kubernetes-sigs/kind/blob/bf63502ed1dfdee6c898ee5cc4318b89f0e09980/pkg/internal/env/term.go#L75

Failing run: [4876437285](https://github.com/knative-sandbox/kn-plugin-event/runs/4876437285?check_suite_focus=true) blocks a PR https://github.com/knative-sandbox/kn-plugin-event/pull/144

This false positive should not be raised, as this is a legal emoji - a variant emoji: https://mothereff.in/utf-8#%F0%9F%A4%B7%E2%80%8D%E2%99%82%EF%B8%8F

Alternatively, adding the exclude list (a file in project) could help battle those kinds of false positives.

**Comment by pierDipi** [comment]
> Alternatively, adding the exclude list (a file in project) could help battle those kinds of false positives.

This is already supported, see https://github.com/pierDipi/unicode-control-characters-action/tree/main/src

**Comment by pierDipi** [comment]
(I'm closing this issue since the exclude list feature is supported)

**Comment by cardil** [comment]
So, I suppose we should check for existence of config file withing the project, and if so use the `-c` option?

**Comment by pierDipi** [comment]
Yes, that is the idea.
